version: 1.0.0.{build}.{branch}
os: Visual Studio 2019

init:
- git config --global core.autocrlf true

nuget:
  account_feed: true
  
services:
  - mssql2014

cache:
  - '%APPDATA%\npm-cache'             # npm cache
  
build_script:
 - cmd: cd src/WilderBlog.Data
 - cmd: dotnet restore 
 - cmd: dotnet build 
 - cmd: cd ../WilderBlog
 - cmd: dotnet restore 
 - cmd: dotnet build 


