version: 1.0.0.{build}.{branch}
os: Visual Studio 2019

init:
- git config --global core.autocrlf true

nuget:
  account_feed: true
  
services:
  - mssql2014

cache:
  - '%APPDATA%\npm-cache'             # npm cache
  
before_build: 
 - cmd: npm install gulp bower -g

build_script:
 - cmd: dotnet restore 
 - cmd: dotnet build 


