version: 1.0.0.{build}.{branch}
os: Visual Studio 2015

init:
- git config --global core.autocrlf true
- cmd: >-
    choco install dotnetcore

    set PATH=C:\Program Files\dotnet\bin;%PATH%

nuget:
  account_feed: true
  
services:
  - mssql2014

cache:
  - '%APPDATA%\npm-cache'             # npm cache
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 
before_build:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - cmd: dotnet restore ./src/WilderBlog.Data
 - cmd: dotnet restore ./src/WilderBlog.Commands
 - cmd: dotnet restore ./src/WilderBlog
 - cmd: npm install gulp bower -g

build_script:
 - cmd: dotnet build ./src/WilderBlog.Data
 - cmd: dotnet build ./src/WilderBlog.Commands
 - cmd: dotnet build ./src/WilderBlog


