name: WilderBlog-Deploy

on: 
  push:
    branches: 
      - Live

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: wmcontainers.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t wmcontainers.azurecr.io/wilderblog:latest
          docker wmcontainers.azurecr.io/wilderblog:latest
