name: WilderBlog-Deploy

on: 
  push:
    branches: 
      - Live

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - uses: azure/docker-login@v1
        with:
          login-server: wmcontainers.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Building Docker Images
        run: |
          docker build .. -f .\Dockerfile --force-rm -t wmcontainers.azurecr.io/wilderblog:test
          docker push wmcontainers.azurecr.io/wilderblog:test
