name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup .NET Core
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    #- name: Add NPM
    #  run: npm install
    #- name: Gulp Clean
    #  run: node node_modules/gulp/bin/gulp.js clean
    #- name: Gulp Minify
    #  run: node node_modules/gulp/bin/gulp.js minify
    #- name: Gulp Scripts
    #  run: node node_modules/gulp/bin/gulp.js scripts
    - name: Build with dotnet
      run: dotnet build --configuration Release
